" ------------------------------------------------------------------------------
" # Vimrc
" ------------------------------------------------------------------------------
" # This is my parent vimrc config, where I setup my defaults and source
" # all of my plugins and config files using a plugin called Sourcery
" # For more info, see https://github.com/jesseleite/vim-sourcery


" ------------------------------------------------------------------------------
" # Vim 8 Defaults
" ------------------------------------------------------------------------------
" # For more info, see :help defaults.vim

unlet! skip_defaults_vim
silent! source $VIMRUNTIME/defaults.vim


" ------------------------------------------------------------------------------
" # Sourcing
" ------------------------------------------------------------------------------

let g:sourcery#vimrc_path = $HOME . '/.dotfiles/vim'

call plug#begin('~/.vim/plugged')
  execute 'source' g:sourcery#vimrc_path . '/plugins.vim'
call plug#end()

call sourcery#source()
