#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       float
yabai -m config top_padding                  40
yabai -m config bottom_padding               40
yabai -m config left_padding                 40
yabai -m config right_padding                40
yabai -m config window_gap                   40

# specific space settings
yabai -m config --space 2 layout             bsp

# specific app settings
yabai -m rule --add app=".*" manage=off
yabai -m rule --add app="kitty" manage=on
yabai -m rule --add app="Google Chrome" manage=on
yabai -m rule --add app="Slack" title!="call" manage=on
yabai -m rule --add app="Discord" title!="^Discord Updater$" manage=on
yabai -m rule --add app="Tower" title!="^Window$" manage=on
yabai -m rule --add app="Ray" manage=on
yabai -m rule --add app="TablePlus" manage=on
yabai -m rule --add app="Paw" title!="^$" manage=on
yabai -m rule --add app="Gitter" manage=on
yabai -m rule --add app="^Music$" space=^1
yabai -m rule --add app="^Mimestream$" space=^1

# signal example
# yabai -m signal --add app="^Ray$" event=window_moved action="yabai -m window $YABAI_WINDOW_ID --resize abs:1920:1080"

# # https://github.com/koekeishiya/yabai/issues/945
# yabai -m rule --add title="Slack call" manage=off
# yabai -m signal --add title="Slack call" event=window_title_changed action="yabai -m window $YABAI_WINDOW_ID --toggle float"

# where is this even output?
echo "yabai configuration loaded.."
