[character]
success_symbol = '[❱](green)'
error_symbol = '[❱](red)'
vimcmd_symbol = '[❱](yellow)'

[directory]
truncation_length = 25
truncate_to_repo = false
style = '006'

[git_branch]
style = '005'

[git_status]
stashed = ''
style = '242'

[php]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[golang]
disabled = true

[elixir]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true
