# ------------------------------------------------------------------------------
# Zshrc
# ------------------------------------------------------------------------------
# This file sets up my basic zsh environment.  Here I set a few defaults,
# paths, and source the rest of the config files as necessary.  Most
# plugins are installed and sourced via brew or antidote, with
# more elaborate configuration in the /local directory.


# ------------------------------------------------------------------------------
# Dotfiles
# ------------------------------------------------------------------------------

DOTFILES="$HOME/.dotfiles"
PATH=$DOTFILES/bin:$PATH


# ------------------------------------------------------------------------------
# Homebrew
# ------------------------------------------------------------------------------

HOMEBREW_NO_AUTO_UPDATE=1
HOMEBREW_PREFIX="/opt/homebrew"
HOMEBREW_CELLAR="/opt/homebrew/Cellar"
HOMEBREW_REPOSITORY="/opt/homebrew"
PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}"
MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"


# ------------------------------------------------------------------------------
# Mise Shims
# ------------------------------------------------------------------------------

PATH=$HOME/.local/share/mise/shims:$PATH


# ------------------------------------------------------------------------------
# Antidote
# ------------------------------------------------------------------------------

source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote load $DOTFILES/zsh/bundles


# ------------------------------------------------------------------------------
# Starship
# ------------------------------------------------------------------------------

eval "$(starship init zsh)"


# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

# Run dotfiles installer
alias dotinstall="$DOTFILES/install"

# Source zshrc
sz() {
  rm -rf $DOTFILES/zsh/bundles.zsh
  source $HOME/.zshrc
  echo 'Sourced zshrc'
}


# ------------------------------------------------------------------------------
# Post Boot
# ------------------------------------------------------------------------------

# Ensure attached to tmux session
tmux_ensure_session
