# ------------------------------------------------------------------------------
# Zshrc
# ------------------------------------------------------------------------------
# This file sets up my basic zsh environment.  Here I set a few defaults,
# paths, and source the rest of the config files as necessary.  Most
# plugins are installed and sourced via brew or antibody, with
# more elaborate configuration in the /local directory.


# ------------------------------------------------------------------------------
# Homebrew
# ------------------------------------------------------------------------------

HOMEBREW_NO_AUTO_UPDATE=1
HOMEBREW_PREFIX="/opt/homebrew"
HOMEBREW_CELLAR="/opt/homebrew/Cellar"
HOMEBREW_REPOSITORY="/opt/homebrew"
PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}"
MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"


# ------------------------------------------------------------------------------
# Sourcing
# ------------------------------------------------------------------------------

# Disable completion directory permission verification
ZSH_DISABLE_COMPFIX=true

# Set oh-my-zsh path
ZSH=$(antibody path robbyrussell/oh-my-zsh)

# Source compiled antibody bundles and configs
[ -f ~/.dotfiles/zsh/bundles.sh ] && source ~/.dotfiles/zsh/bundles.sh


# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------

PATH=~/.dotfiles/bin:$PATH
PATH=./node_modules/.bin:$PATH
PATH=~/.composer/vendor/bin:$PATH
PATH=./vendor/bin:$PATH


# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

# Compile bundles and source zshrc
sz() {
  sh ~/.dotfiles/zsh/bundles_compile
  source ~/.zshrc
  echo 'Sourced zshrc'
}

# Run dotfiles installer
alias dotinstall="~/.dotfiles/install"


# ------------------------------------------------------------------------------
# Post Boot
# ------------------------------------------------------------------------------

# Ensure attached to tmux session
tmux_ensure_session
